routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register' => false]);

Route::get('/', function () {
    return view('welcome');
});

Route::get('painel', function () {
    return redirect()->route('login');
});

Route::group(['prefix' => 'panel', 'as' => 'panel.', 'middleware' => ['auth'], 'namespace' => 'Panel'], function () {
    Route::get('dashboard', 'PanelController@index')->name('index');
    Route::get('profile', 'UserController@selfUpdate')->name('user.profile');

    Route::get('users', 'UserController@index')->name('user.index');
    Route::get('user/create', 'UserController@create')->name('user.create');
    Route::post('user', 'UserController@store')->name('user.store');
    Route::get('user/{idUser}/show', 'UserController@show')->name('user.show');
    Route::get('user/{idUser}/edit', 'UserController@edit')->name('user.edit');
    Route::put('user/{idUser}', 'UserController@update')->name('user.update');
    Route::delete('user/{idUser}', 'UserController@destroy')->name('user.destroy');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public static function rules($is_update = false)
    {
        $rules = [
            'name' => ['string', 'required', 'max:191'],
            'email' => ['required', 'string', 'email', $is_update ? '' : 'unique:users,email', 'max:191'],
            'password' => ($is_update && empty(request()->password)) ? [] : ['required', 'string', 'min:6'],
        ];

        return $rules;
    }

    public function setPasswordAttribute($value)
    {
        if (!empty($value)) {
            $this->attributes['password'] = Hash::make($value);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Panel/PanelController.php
<?php

namespace App\Http\Controllers\Panel;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PanelController extends Controller
{
    public function index(Request $request)
    {
        return view('panel.index');
    }
}

app/Http/Controllers/Panel/UserController.php
<?php

namespace App\Http\Controllers\Panel;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\StoreRequest;
use App\Http\Requests\User\UpdateRequest;
use App\User;

class UserController extends Controller
{

    public function index()
    {
        $this->authorize('index', User::class);
        $registros = User::all()->sortByDesc('id');
        return view('panel.user.index', compact('registros'));
    }

    public function create()
    {
        $this->authorize('create', User::class);
        return view('panel.user.create');
    }

    public function store(StoreRequest $request)
    {
        $this->authorize('create', User::class);
        try {
            User::create($request->input());
        } catch (\Exception $e) {
            dd($e);
        }
        return redirect()->route('panel.user.index')
            ->with('success', 'Perfil criado com sucesso.');
    }

    public function show(User $registro)
    {
        //
    }

    public function edit(User $registro)
    {
        $user = $registro ?? auth()->user();
        $this->authorize('edit', $user);
        return view('panel.user.edit', compact('registro'));
    }

    public function update(UpdateRequest $request, User $registro)
    {
        $user = $registro ?? auth()->user();
        $this->authorize('edit', $user);
        try {
            $registro->update($request->input());
        } catch (\Exception $e) {
            dd($e);
        }
        if (auth()->user()->can('index', auth()->user())) {
            return redirect()->route('panel.user.index')
                ->with('success', 'Perfil atualizado com sucesso.');
        } else {
            return redirect()->route('panel.user.profile')
                ->with('success', 'Perfil atualizado com sucesso.');
        }
    }

    public function destroy(User $registro)
    {
        $this->authorize('destroy', User::class);
        try {
            $registro->delete();
        } catch (\Exception $e) {
            dd($e);
        }
        return redirect()->route('panel.user.index')
            ->with('success', 'Perfil deletado com sucesso.');
    }

    public function selfUpdate()
    {
        $this->authorize('edit', auth()->user());
        $registro = auth()->user();
        return view('panel.user.edit', compact('registro'));
    }
}

resources/views/includes/alert.blade.php
@if (\Session::has('success'))
<div class="alert alert-success">
  {!! \Session::get('success') !!}
</div>
@endif
@if (\Session::has('errors'))
<div class="alert alert-danger">
  {!! \Session::get('errors')->first() !!}
</div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="/panel/js/app.js" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="/panel/css/app.css" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/login.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title> {{ env('APP_NAME') }} - @yield('title', 'Login')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/panel/css/app.css">
</head>

<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <a href="#"><b>Acessar </b>Painel</a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
      <div class="card-body login-card-body">
        <p class="login-box-msg">Insira os dados para acessar</p>

        <form action="{{route('login')}}" method="post">
          @csrf
          <div class="input-group mb-3">
            <input name="email" type="email" autocomplete="username" class="form-control" placeholder="Email">
            <div class="input-group-append input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
          <div class="input-group mb-3">
            <input name="password" type="password" autocomplete="current-password" class="form-control" placeholder="Password">
            <div class="input-group-append input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
          <div class="row">
            <div class="col-8">
              <div class="icheck-primary">
                <input type="checkbox" id="remember">
                <label for="remember">
                  Lembrar-me
                </label>
              </div>
            </div>
            <!-- /.col -->
            <div class="col-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Acessar</button>
            </div>
            <!-- /.col -->
          </div>
        </form>



        {{-- <div class="social-auth-links text-center mb-3">
          <p>- OR -</p>
          <a href="#" class="btn btn-block btn-primary">
            <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
          </a>
          <a href="#" class="btn btn-block btn-danger">
            <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
          </a>
        </div> --}}
        <!-- /.social-auth-links -->
        @if(Route::has('password.request'))
        <p class="mb-1">
          <a href="{{route('password.request')}}">I forgot my password</a>
        </p>
        @endif
        @if(Route::has('register'))
        <p class="mb-0">
          <a href="{{route('register')}}" class="text-center">Register a new membership</a>
        </p>
        @endif
      </div>
      <!-- /.login-card-body -->
    </div>
  </div>
  <!-- /.login-box -->
  <script src="/panel/js/app.js"></script>

</body>

</html>

resources/views/layouts/panel.blade.php
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>@yield('title', 'Painel')</title>

  <link rel="stylesheet" href="/panel/css/app.css">
  @yield('css')
</head>

<body class="hold-transition sidebar-mini">
  <div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
      </ul>
      {{-- <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
          <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-navbar" type="submit">
              <i class="fas fa-search"></i>
            </button>
          </div>
        </div>
      </form> --}}

      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto">
        <!-- Authentication Links -->
        @guest
        <li class="nav-item">
          <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
        </li>
        <li class="nav-item">
          @if (Route::has('register'))
          <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
          @endif
        </li>
        @else
        @endguest
      </ul>

      <!-- SEARCH FORM -->
    </nav>
    <!-- /.navbar -->

    @include('layouts.partials.main-sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">@yield('content_header')</h1>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-12">
              @yield('content')
            </div>
          </div>
        </div>
      </div>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="float-right d-none d-sm-inline">
        Como podemos mudar seu mundo hoje?
      </div>
      <!-- Default to the left -->
      <strong>2019-{{\Carbon\Carbon::now()->year}} <a href="//infojr.com.br">InfoJr UFBA</a></strong>
    </footer>
  </div>
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
  <script src="/panel/js/app.js"></script>
  @yield('js')
</body>

</html>

resources/views/layouts/partials/main-sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="{{route('panel.index')}}" class="brand-link">
    <img src="/panel/img/logo.png" alt="logomarca" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">{{ config('app.name', 'Laravel') }}</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="/panel/img/profile.png" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{auth()->user()->name}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        @can('index', App\User::class)
        <li class="nav-item">
          <a class="nav-link {{ (Route::currentRouteName() == 'panel.user.index') ? 'active' : ''}}"
            href="{{route('panel.user.index')}}">
            <i class="nav-icon fas fa-users blue"></i>
            <p>
              Manter Usuários
            </p>
          </a>
        </li>
        @endcan

        <hr />
        @if(auth()->user()->can('edit', [App\User::class, auth()->user()]))
        <li class="nav-item">
          <a href="{{route('panel.user.profile')}}"
            class="nav-link {{ (Route::currentRouteName() == 'panel.user.profile') ? 'active' : ''}}">
            <i class="nav-icon fas fa-user blue"></i>
            <p>
              Meu Perfil
            </p>
          </a>
        </li>
        @endif

        @if(auth()->check())
        <li class="nav-item">
          <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();">
            <i class="nav-icon fa fa-power-off red"></i>
            <p>
              {{ __('Logout') }}
            </p>
          </a>
          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
          </form>
        </li>
        @endif

      </ul>
    </nav>

    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

resources/views/panel/index.blade.php
@extends('layouts.panel')

@section('title', 'Painel')

@section('content_header')
<h1>Dashboard</h1>
@stop

@section('content')
<div class="card">
    <div class="card-header">
        <span class="card-title">Meu Dashboard</span>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            <button type="button" class="btn btn-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i></button>
        </div>
    </div>
    <div class="card-body">
        <div class="row">
        </div>
    </div>
    {{-- <div class="card-footer">
        Footer
    </div> --}}
</div>
@stop

resources/views/panel/user/_form.blade.php
<div class="card-body">
    <div class="form-group row">

        {!! Form::label('email', 'E-mail', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-3 ">
            {!! Form::text('email',null,['class' => 'form-control input-jqv', 'id' => 'email', 'autocomplete' =>
            'username' ]) !!}
        </div>
        @error('name')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        {!! Form::label('password', 'Senha', ['class' => 'col-sm-1 control-label']) !!}
        <div class=" col-sm-3">
            {!! Form::password('password',['class' => 'form-control input-jqv', 'id' => 'password', 'autocomplete' =>
            'new-password', 'data-toggle' => 'password']) !!}
            <div class="input-group-append">
                <span class="input-group-text input-password-hide" style="cursor: pointer;"><i
                        class="fa fa-eye"></i></span>
            </div>
            @error('password')
            <span class="invalid-feedback d-block"> {{ $message }} </span>
            @enderror
        </div>

        {!! Form::label('name', 'Nome Completo', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-3">
            {!! Form::text('name',null,['class' => 'form-control input-jqv', 'id' => 'name']) !!}
        </div>
        @error('name')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        
    </div>

    {{-- <div class="form-group row">
        {!! Form::label('tax', 'CPF', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-3">
            {!! Form::text('tax',null,['class' => 'form-control input-jqv cpf', 'id' => 'tax']) !!}
        </div>
        @error('tax')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        {!! Form::label('birth', 'Dt. Nasc.', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-3">
            {!! Form::text('birth',null,['class' => 'form-control input-jqv placeholder datepicker', 'id' => 'birth',
            // 'data-provide' => "datepicker",
            ]) !!}
        </div>
        @error('birth')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
    </div> --}}

    {{-- <div class="form-group row">

        {!! Form::label('phone_area', 'DDD', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-1">
            {!! Form::text('phone_area',null,['class' => 'form-control input-jqv', 'id' => 'phone_area']) !!}
        </div>
        @error('phone_area')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror

        {!! Form::label('phone_number', 'Telefone', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-2">
            {!! Form::text('phone_number',null,['class' => 'form-control input-jqv', 'id' => 'phone_number']) !!}
        </div>
        @error('phone_number')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        {!! Form::label('address_zip', 'CEP', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-2">
            {!! Form::text('address_zip',null,['class' => 'form-control input-jqv cep', 'id' => 'cep',
            // 'data-provide' => "datepicker",
            ]) !!}
        </div>
        @error('address_zip')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        {!! Form::label('address_city', 'Cidade', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-2">
            {!! Form::text('address_city',null,['class' => 'form-control input-jqv', 'id' => 'cidade']) !!}
        </div>
        @error('address_city')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
        <div class="col-sm-1">
            {!! Form::text('address_state',null,['class' => 'form-control input-jqv', 'id' => 'uf',
            'placeholder' => 'UF']) !!}
        </div>
        @error('address_state')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror
    </div> --}}

    {{-- <div class="form-group row">

        {!! Form::label('address_street', 'Rua', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-4">
            {!! Form::text('address_street',null,['class' => 'form-control input-jqv', 'id' => 'rua']) !!}
        </div>
        @error('address_street')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror

        {!! Form::label('address_district', 'Bairro', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-4">
            {!! Form::text('address_district',null,['class' => 'form-control input-jqv', 'id' => 'bairro']) !!}
        </div>
        @error('address_district')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror

        {!! Form::label('address_number', 'Num.', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-1">
            {!! Form::text('address_number',null,['class' => 'form-control input-jqv', 'id' => 'address_number', 'placeholder' =>
            'Núm.']) !!}
        </div>
        @error('address_number')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror

    </div> --}}

    {{-- <div class="form-group row">
        {!! Form::label('address_complement', 'Complemento', ['class' => 'col-sm-1 control-label']) !!}
        <div class="col-sm-4">
            {!! Form::text('address_complement',null,['class' => 'form-control input-jqv', 'id' => 'address_complement']) !!}
        </div>

        @error('address_complement')
        <span class="invalid-feedback d-block"> {{ $message }} </span>
        @enderror

    </div> --}}

</div>

<div class="card-footer">
    <div class="box-footer">
        <a class="btn btn-danger float-right"
            href="{{ (auth()->user()->can('index', [App\User::class, auth()->user()])) ? route('panel.user.index') : route('panel.index') }}">Voltar</a> {!!
        Form::submit('Salvar',['class'
        => 'btn btn-primary pull-left']) !!}
    </div>
</div>
@section('css')
<link rel="stylesheet" href="/panel/js/plugins/jquery-ui/jquery-ui.min.css">
@endsection
@section('js_form')
<script type="text/javascript" src="/panel/js/via-cep.js"></script>
<script type="text/javascript" src="/panel/js/plugins/jquery-ui/jquery-ui.min.js"></script>
<script>
    $(document).ready(function() {
            // $("#form_id").validate();
            $('.datepicker').datepicker({
                dateFormat: 'dd/mm/yy',
                dayNames: ['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'],
                dayNamesMin: ['D','S','T','Q','Q','S','S','D'],
                dayNamesShort: ['Dom','Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
                monthNames: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
                monthNamesShort: ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'],
                nextText: 'Próximo',
                prevText: 'Anterior'
            });
        });
</script>
@stop

resources/views/panel/user/create.blade.php
@extends('layouts.panel')

@section('title', 'Cadastro de Usuários')

@section('content')
@include('includes.alert')
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">Cadastro de Usuários</h3>
    </div>
    {!! Form::open([
    'route' => 'panel.user.store',
    'files' => true,
    'class' => 'form-horizontal',
    'id' => 'form_id'
    ]) !!}
    @include('panel.user._form')
    {!! Form::close() !!}
</div>
@stop

@section('js')
    <script type="text/javascript" src="/vendor/jsvalidation/js/jsvalidation.js"></script>
    {!! JsValidator::formRequest('App\Http\Requests\User\StoreRequest', '#form_id'); !!}
@yield('js_form')
@endsection

resources/views/panel/user/index.blade.php
@extends('layouts.panel')

@section('title', 'Manter Usuários')
@section('css')
<!-- DataTables -->
<link rel="stylesheet" href="/panel/js/plugins/datatables/dataTables.bootstrap4.css">
@endsection
@section('content')
<div class="card">
    <!-- /.card-header -->
    @include('includes.alert')
    <div class="card-header">
        <a href="{{ route('panel.user.create') }}" class="btn btn-primary float-left" role="button">Adicionar
            Registro</a>
    </div>
    <div class="card-body">
        <div id="datatable_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
                <div class="col-sm-12">
                    <table id="datatable" class="table table-bordered table-hover dataTable" role="grid">
                        <thead>
                            <tr role="row">
                                <th>Nome</th>
                                <th>E-mail</th>
                                <th style="width:175px">Ações</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($registros as $item)
                            <tr>
                                <td>{{$item->name}}</td>
                                <td>{{$item->email}}</td>
                                <td>
                                    <a class="btn btn-primary btn-sm" href="{{route('panel.user.edit', $item->id)}}">
                                        <i class="fa fa-pencil-alt white"></i> Editar
                                    </a>
                                    /
                                    <a class="btn btn-danger btn-sm" href="#" data-toggle="modal"
                                        data-target="#deleteRatificationModal-{{$item->id}}">
                                        <i class="fa fa-trash white"></i> Apagar
                                    </a>
                                </td>
                            </tr>
                            <div class=" modal fade" id="deleteRatificationModal-{{$item->id}}" role="dialog"
                                aria-labelledby="ratificationMsg" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="ratificationMsg">
                                                Confirmar exclusão
                                            </h4>
                                        </div>
                                        <div class="modal-body">
                                            Quer mesmo deletar este registro?
                                        </div>
                                        <div class="modal-footer">
                                            <form method="POST" action="{{ route('panel.user.destroy', $item->id ) }}">
                                                @method('DELETE') @csrf
                                                <button type="button" class="btn btn-primary"
                                                    data-dismiss="modal">Cancelar</button>
                                                <input type="submit" name="submit" value="Delete"
                                                    class='btn btn-danger'>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-body -->
</div>
@stop

@section('js')
<!-- DataTables -->
<script src="/panel/js/plugins/datatables/jquery.dataTables.js"></script>
<script src="/panel/js/plugins/datatables/dataTables.bootstrap4.js"></script>
<script>
    $(function () {
        $("#datatable").DataTable({
            "ordering": false,
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Portuguese-Brasil.json"
            }
        });
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
        });
    });
</script>
@stop